<h2> Tahapan </h2>

1. install python
2. install vs code
3. buat project di file explorer
4. buka project tersebut/direktori/folder di vs code
5. buat file baru dengan ekstensi .ipynb

In [1]:
print ("hello")

hello

Menggunakan library untuk mengolah data
- memasang library (pandas, numpy, matlotlib, seaborn, scikit-learn jupyter)
- memasangnya melalui terminal
- jalankan perintah pip install (library yang akan dipasang)

mengimport/mengambil library yang akan kita gunakan

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#untuk menangani missing value
from sklearn.impute import KNNImputer 
#untuk mendeteksi outlier
from sklearn.neighbors import LocalOutlierFactor 

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)

print("libraries sudah selesai di import")

libraries sudah selesai di import

Membuat daaset kotor
1. kita akan buat 150 record dataset, data mahasiswa, 8 atribut
2. dataset berisi duplikat data
3. dataset berisi mising value
4. dataset berisi outlier/anomali data
5. dataset berisi data yang tidak konsisten

In [6]:
data = {
    "NIM": [
        "23001", "23002", "23003", "23004",
        "23005", "23006", "23007", "23008",
        "23009", "23010", "23011", "23011"
    ],
    "Nama": [
        "Andi", "Siti", "Budi", "Rina",
        "Dedi", "Ani", "Rudi", "Dina",
        "Tono", "Lina", "Fajar", "Fajar"
    ],
    "Prodi": [
        "Informatika", "Sistem Informasi", "Informatka",
        "Informatika", "Sistem Informasi", "Informatika",
        "Sistem Informasi", "Informatika", None,
        "Sistem Informasi", "Informatika", "Informatika"
    ],
    "Umur": [
        20, 21, 19, 22, None, 20,
        21, 19, 20, 150, 21, 21
    ],
    "Nilai_Tugas": [
        80, 85, 75, None, 90, 88,
        78, 82, 85, 95, 80, 80
    ],
    "Nilai_UTS": [
        78, 90, 70, 85, 92, None,
        75, 80, 88, 98, 79, 79
    ],
    "Nilai_Akhir": [
        79, 88, 72, 85, 91, 86,
        76, 81, 87, 96, 80, 80
    ]
}
#menampilkan data

df = pd.DataFrame(data)
df

      NIM   Nama             Prodi   Umur  Nilai_Tugas  Nilai_UTS  Nilai_Akhir
0   23001   Andi       Informatika   20.0         80.0       78.0           79
1   23002   Siti  Sistem Informasi   21.0         85.0       90.0           88
2   23003   Budi        Informatka   19.0         75.0       70.0           72
3   23004   Rina       Informatika   22.0          NaN       85.0           85
4   23005   Dedi  Sistem Informasi    NaN         90.0       92.0           91
5   23006    Ani       Informatika   20.0         88.0        NaN           86
6   23007   Rudi  Sistem Informasi   21.0         78.0       75.0           76
7   23008   Dina       Informatika   19.0         82.0       80.0           81
8   23009   Tono               NaN   20.0         85.0       88.0           87
9   23010   Lina  Sistem Informasi  150.0         95.0       98.0           96
10  23011  Fajar       Informatika   21.0         80.0       79.0           80
11  23011  Fajar       Informatika   21.0         80.0       79.0           80

In [17]:
df = pd.read_csv("dataset_mahasiswa_kotor_150.csv")
df

            NIM              Nama Jenis_Kelamin       Program_Studi  Angkatan   IPK  Umur Status_Mahasiswa
0    TI20240001     Wahyu Pratama             L           Manajemen    2023.0  3.37  21.0            Aktif
1    TI20240002      Alya Pratama             L           Akuntansi    2022.0  3.09  18.0            Aktif
2    TI20240003       Gita Wijaya             L    Sistem Informasi    2025.0  3.44  21.0             Cuti
3    TI20240004      Tono Nugroho             L    Sistem Informasi    2025.0   NaN  23.0             Cuti
4    TI20240005               NaN             P  Teknik Informatika    2022.0  3.04  24.0            Aktif
..          ...               ...           ...                 ...       ...   ...   ...              ...
145  TI20230146     Hana Ramadhan             P    Sistem Informasi    2025.0  3.50  18.0             Cuti
146  TI20230147       Alya Kusuma             P           Akuntansi    2023.0   NaN  25.0            Aktif
147  TI20230148       Eko Purnama             P  Teknik Informatika    2025.0  2.56  19.0         Nonaktif
148  TI20230149       Yoga Kusuma             L    Sistem Informasi    2025.0  3.38  20.0            Aktif
149  TI20230150  Putri Firmansyah             P           Manajemen    2025.0  3.28  19.0             Cuti

[150 rows x 8 columns]

memeriksa kondisi dataset

In [11]:
print("ukuran dataset: ", df.shape)
print ("\nInformasi dataset:")
df.info()

ukuran dataset:  (150, 8)

Informasi dataset:
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   NIM               148 non-null    str
 1   Nama              146 non-null    str
 2   Jenis_Kelamin     147 non-null    str
 3   Program_Studi     147 non-null    str
 4   Angkatan          147 non-null    float64
 5   IPK               144 non-null    float64
 6   Umur              146 non-null    float64
 7   Status_Mahasiswa  147 non-null    str
dtypes: float64(3), str(5)
memory usage: 9.5 KB

In [12]:
#tampilkan 5 data pertama
display(df.head(5))

          NIM           Nama Jenis_Kelamin       Program_Studi  Angkatan   IPK  Umur Status_Mahasiswa
0  TI20240001  Wahyu Pratama             L           Manajemen    2023.0  3.37  21.0            Aktif
1  TI20240002   Alya Pratama             L           Akuntansi    2022.0  3.09  18.0            Aktif
2  TI20240003    Gita Wijaya             L    Sistem Informasi    2025.0  3.44  21.0             Cuti
3  TI20240004   Tono Nugroho             L    Sistem Informasi    2025.0   NaN  23.0             Cuti
4  TI20240005            NaN             P  Teknik Informatika    2022.0  3.04  24.0            Aktif

In [13]:
#memeriksa statistik deskriptif
df.describe(include='all')

               NIM          Nama Jenis_Kelamin Program_Studi     Angkatan         IPK        Umur Status_Mahasiswa
count          148           146           147           147   147.000000  144.000000  146.000000              147
unique         143           113             5             7          NaN         NaN         NaN                6
top     TI20240010  Tono Nugroho             P     Akuntansi          NaN         NaN         NaN         Nonaktif
freq             2             3            73            39          NaN         NaN         NaN               61
mean           NaN           NaN           NaN           NaN  2022.687075    3.134028   22.547945              NaN
std            NaN           NaN           NaN           NaN    10.250161    0.748141   10.455213              NaN
min            NaN           NaN           NaN           NaN  1900.000000   -0.500000   12.000000              NaN
25%            NaN           NaN           NaN           NaN  2022.000000    2.875000   20.000000              NaN
50%            NaN           NaN           NaN           NaN  2024.000000    3.125000   22.000000              NaN
75%            NaN           NaN           NaN           NaN  2024.500000    3.382500   24.000000              NaN
max            NaN           NaN           NaN           NaN  2025.000000    9.750000  145.000000              NaN

memeriksa statistik deskriptif

In [14]:
#memeriksa missing value aatau nilai yang hilang
print("Jumlah miising value:" )
print (df.isnull().sum())

Jumlah miising value:
NIM                 2
Nama                4
Jenis_Kelamin       3
Program_Studi       3
Angkatan            3
IPK                 6
Umur                4
Status_Mahasiswa    3
dtype: int64

In [18]:
#memeriksa jumlah baris yang duplikat
print ("Jumlah baris duplikat: ")
print (df.duplicated().sum())

Jumlah baris duplikat:
5

In [20]:
#memeriksa persentase missing value
print("Persentase missing value:")
print ((df.isnull().mean()*100).round(2))

Persentase missing value:
NIM                 1.33
Nama                2.67
Jenis_Kelamin       2.00
Program_Studi       2.00
Angkatan            2.00
IPK                 4.00
Umur                2.67
Status_Mahasiswa    2.00
dtype: float64

In [21]:
#Mulai membersihkan data
#menghapus data duplikat dan memperbaiki inkonsistensi

print ("jumlah bais sebelum:", len(df))
df=df.drop_duplicates(subset=["NIM"], keep="first")

print ("jumlah baris setelah:", len(df))

jumlah bais sebelum: 150
jumlah baris setelah: 144

In [23]:
df["Jenis_Kelamin"]=df["Jenis_Kelamin"].replace({"Laki-laki":"L", "Perempuan":"P"})
df["Jenis_Kelamin"]=df["Jenis_Kelamin"].str.strip()

df

            NIM              Nama Jenis_Kelamin       Program_Studi  Angkatan   IPK  Umur Status_Mahasiswa
0    TI20240001     Wahyu Pratama             L           Manajemen    2023.0  3.37  21.0            Aktif
1    TI20240002      Alya Pratama             L           Akuntansi    2022.0  3.09  18.0            Aktif
2    TI20240003       Gita Wijaya             L    Sistem Informasi    2025.0  3.44  21.0             Cuti
3    TI20240004      Tono Nugroho             L    Sistem Informasi    2025.0   NaN  23.0             Cuti
4    TI20240005               NaN             P  Teknik Informatika    2022.0  3.04  24.0            Aktif
..          ...               ...           ...                 ...       ...   ...   ...              ...
145  TI20230146     Hana Ramadhan             P    Sistem Informasi    2025.0  3.50  18.0             Cuti
146  TI20230147       Alya Kusuma             P           Akuntansi    2023.0   NaN  25.0            Aktif
147  TI20230148       Eko Purnama             P  Teknik Informatika    2025.0  2.56  19.0         Nonaktif
148  TI20230149       Yoga Kusuma             L    Sistem Informasi    2025.0  3.38  20.0            Aktif
149  TI20230150  Putri Firmansyah             P           Manajemen    2025.0  3.28  19.0             Cuti

[144 rows x 8 columns]

In [24]:
#cek dataset dengan nilai yang tidak konsisten
df["Jenis_Kelamin"].value_counts()

Jenis_Kelamin
P            72
L            67
perempuan     1
Pria          1
Name: count, dtype: int64

In [25]:
#mengganti nilai yang tidak konsisten pada kolom jenis kelamin
df["Jenis_Kelamin"]=df["Jenis_Kelamin"].replace({"Laki-laki":"L", "Perempuan":"P"})

In [26]:
#cek dataset dengan nilai yang tidak konsisten
df["Jenis_Kelamin"].value_counts()

Jenis_Kelamin
P            72
L            67
perempuan     1
Pria          1
Name: count, dtype: int64

In [27]:
#mengganti nilai yang tidak konsisten pada kolom jenis kelamin
df["Jenis_Kelamin"]=df["Jenis_Kelamin"].replace({"Pria":"L", "perempuan":"P"})

In [ ]:
#menggunakan KNN Imputer untuk menangani mising value